#' Duplicate objects in the global environment based on names matching a grep pattern.
#'
#' Duplicate multiple ojects in the global environment based on a grep pattern match. This allows modification of one version of the objects without losing the previous versions. Useful for testing modifications to objects generated by time-consuming code. This is a simple wrapper for makeCopy.
#' @param var_pattern character string, the regex pattern to match object names. Passed to \code{grep} via \code{ls_grep}.
#' @param append character string, the text to be appended to the objects' names when making the copies. Defaults to ".old".
#' @param ask logical, whether to prompt the user before copying objects. Defaults to TRUE.
#' @export
#' @usage \code{make_copies(var_pattern, append=".old", ask=TRUE)}
make_copies <- function(var_pattern, append=".old", ask=TRUE) {
  vars_to_copy <- ls_grep(var_pattern)
  if (ask) {
    cat("About to copy the following objects with suffix '", append, "':\n\n", sep="")
    cat(vars_to_copy, sep = "\n")
    proceed <- read_yn("Do you want to proceed? (Enter y or n): ")
    if (proceed == "n") 
      stop("Variables not replaced.")
  }
  invisible(lapply(vars_to_copy, makeCopy))
}
